# Generated by Django 2.2.7 on 2019-11-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='date published')),
            ],
            options={
                'verbose_name': 'todo list',
                'ordering': ['-pub_date'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='complete by date')),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.Todo')),
            ],
        ),
    ]
